services:
  minecraft-bedrock:
    image: itzg/minecraft-bedrock-server:2025.9.0
    restart: always
    environment:
      EULA: "TRUE"
      SERVER_NAME: "Local minecraft server"
      ALLOW_CHEATS: "false"
      ONLINE_MODE: "false"
      VERSION: "1.21.132.1"
    ports:
      - "19132:19132/udp"
    volumes:
      - ./data:/data
